"""Initial migration

Revision ID: 8a189f0771f2
Revises: 
Create Date: 2025-07-12 13:24:22.948832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a189f0771f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_test', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retake_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_test', schema=None) as batch_op:
        batch_op.drop_column('retake_limit')

    # ### end Alembic commands ###
